### ISSUE TITLE
ValueError: Can only compare identically-labeled Series objects

### ISSUE THREAD

**Issue by DirkFries** [AICoE/prometheus-anomaly-detector#102]
Hi @all,

during my first steps I am encountering the following error:

Optimization terminated normally:
  Convergence detected: relative gradient magnitude is below tolerance
2020-02-12 10:33:36,558:INFO:model: training data range: 2020-01-15 16:00:09.177000046 - 2020-01-20 15:59:09.177000046
Initial log joint probability = -8.28816
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
      92       19528.4   7.04715e-07       88.4888      0.1741           1      128
Optimization terminated normally:
  Convergence detected: relative gradient magnitude is below tolerance
Traceback (most recent call last):
  File "test_model.py", line 167, in <module>
    true_values.metric_values, model_mp.predicted_df
  File "test_model.py", line 50, in label_predicted_anomalies
    ((true_value_df["y"] >= predicted_value_df["yhat_upper"]))
  File "/usr/lib64/python3.6/site-packages/pandas/core/ops/__init__.py", line 1142, in wrapper
    raise ValueError("Can only compare identically-labeled " "Series objects")
ValueError: Can only compare identically-labeled Series objects

My first assumption was, that the metric path of my Time Series Data has changed.
e.g. if a VM movies from one ESX Host to another the metric path changes like that:

vsphere_cpu_count_latest{cluster="cluster-win",host="esx1",name="Virtualmachine"}
vsphere_cpu_count_latest{cluster="cluster-win",host="esx2",name="Virtualmachine"}

So I made sure, that me Timeseries Data have a consitent metric path, but the error messages still appears.

Has anyone a hint for me ?

Bye, Dirk

**Comment by hemajv** [comment]
Hey,
so when you compare two DataFrames using `np.where()`, you must ensure that the number of records in the first DataFrame matches with the number of records in the second DataFrame. Can you please print out your `true_value_df` and `predicted_value_df`?

**Comment by DirkFries** [comment]
Hi hemajv,

thanks a lot for your comment. I have to admit that I am a complete newbie to Prometheus Anomaly Detector and all I got as documentation is the readme file here at github. 

I started the run with the following options:

```
export FLT_PROM_URL="http://testhost:9092"
export FLT_METRICS_LIST="vsphere_cpu_usage_maximum{name=host'}"
export FLT_ROLLING_TRAINING_WINDOW_SIZE=5d
export FLT_DATA_START_TIME="2020-01-01 18:00:00"
export FLT_DATA_END_TIME="2020-01-10 18:00:00"
export MLFLOW_TRACKING_URI="http://127.0.0.1:5000"
```

Where can I configure `np_where()` or check true_value_df and `predicted_value_df`

Thanks!

Bye, Dirk

**Comment by 4n4nd** [comment]
This should be in your `test_model.py`
You can do this by adding the following statement at [line 47](https://github.com/AICoE/prometheus-anomaly-detector/blob/master/test_model.py#L47):
```python
        print(true_value_df, predicted_value_df)
```

**Comment by DirkFries** [comment]
Hi @all,

I tried Anand's suggestion and I get indeed much more output (.. although I have to admit I don't really understand it ... )

```
host:~/pad/prometheus-anomaly-detector-master # time python test_model.py
2020-02-14 09:33:11,024:INFO:test_configuration: Metric train data start time: 2020-01-01 18:00:00
2020-02-14 09:33:11,024:INFO:test_configuration: Metric train data end time/test data start time: 2020-01-06 17:59:59.957954
2020-02-14 09:33:11,024:INFO:test_configuration: Metric test end time: 2020-01-10 18:00:00
2020-02-14 09:33:11,024:INFO:test_configuration: Metric data rolling training window size: 4 days, 23:59:59.957954
2020-02-14 09:33:11,025:INFO:test_configuration: Model retraining interval: 120 minutes
2020-02-14 09:33:11,025:INFO:test_configuration: True anomaly threshold: 0.001
2020-02-14 09:33:11,025:INFO:test_configuration: MLflow server url: http://127.0.0.1:5000
/usr/lib64/python3.6/site-packages/Cython/Build/Inline.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2020-02-14 09:33:14,194:INFO:__main__: Downloaded metric data
2020-02-14 09:33:14,529:INFO:model: training data range: 2020-01-01 17:00:33.640000105 - 2020-01-06 16:59:33.640000105
Initial log joint probability = -14.8391
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
      99       16825.5   1.34005e-05       104.092   1.333e-07       0.001      171  LS failed, Hessian reset
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     111       16825.5   2.57031e-07       103.211      0.4275      0.4275      186
Optimization terminated normally:
  Convergence detected: relative gradient magnitude is below tolerance
2020-02-14 09:33:17,487:INFO:model: training data range: 2020-01-01 19:00:33.640000105 - 2020-01-06 18:59:33.640000105
Initial log joint probability = -14.9558
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
      94       16824.5   4.49127e-07       97.7429      0.2476           1      114
Optimization terminated normally:
  Convergence detected: relative gradient magnitude is below tolerance
                                 y
ds
2020-01-06 19:00:33.640000105  411
2020-01-06 19:01:33.640000105  412
2020-01-06 19:02:33.640000105  417
2020-01-06 19:03:33.640000105  423
2020-01-06 19:04:33.640000105  418
...                            ...
2020-01-06 20:55:33.640000105  403
2020-01-06 20:56:33.640000105  413
2020-01-06 20:57:33.640000105  420
2020-01-06 20:58:33.640000105  607
2020-01-06 20:59:33.640000105  398

[120 rows x 1 columns]                                      yhat  yhat_lower  yhat_upper
timestamp
2020-01-06 19:00:33.640000105  537.378044   87.500528  937.321275
2020-01-06 19:01:33.640000105  537.526576   88.045310  962.774545
2020-01-06 19:02:33.640000105  537.676941  146.540387  959.035153
2020-01-06 19:03:33.640000105  537.829112  111.674334  959.555580
2020-01-06 19:04:33.640000105  537.983057  130.233407  975.375949
...                                   ...         ...         ...
2020-01-06 20:55:33.640000105  557.700459  139.139551  977.214124
2020-01-06 20:56:33.640000105  557.827231  158.980257  958.637565
2020-01-06 20:57:33.640000105  557.952032  133.966893  971.096276
2020-01-06 20:58:33.640000105  558.074847  136.286171  997.806259
2020-01-06 20:59:33.640000105  558.195662  161.369883  971.560434

[120 rows x 3 columns]
Traceback (most recent call last):
  File "test_model.py", line 169, in <module>
    true_values.metric_values, model_mp.predicted_df
  File "test_model.py", line 52, in label_predicted_anomalies
    ((true_value_df["y"] >= predicted_value_df["yhat_upper"]))
  File "/usr/lib64/python3.6/site-packages/pandas/core/ops/__init__.py", line 1142, in wrapper
    raise ValueError("Can only compare identically-labeled " "Series objects")
ValueError: Can only compare identically-labeled Series objects

```

**Comment by 4n4nd** [comment]
so the y column is your real value and the yhat is the predicted value. yhat_upper and yhat_lower are the upper and lower bounds of your prediction. Hema just fixed this issue in her PR, can you please try again with the latest commit?

Thanks!

**Comment by DirkFries** [comment]
Hi Hema and Anand,

the command works now perfectly.
Thanks a lot ! :-)

Bye, Dirk
