### ISSUE TITLE
it seems app.py can't be runned in WINDOWS OS? 

### ISSUE THREAD

**Issue by frankcgq105** [AICoE/prometheus-anomaly-detector#124]
I run app.py in WINDOWS7 system,but it failed,below is the error log:

Traceback (most recent call last):
  File ".\app.py", line 171, in <module>
    server_process.start()
  File "D:\anaconda\envs\stan_env\lib\multiprocessing\process.py", line 112, in
start
    self._popen = self._Popen(self)
  File "D:\anaconda\envs\stan_env\lib\multiprocessing\context.py", line 223, in
_Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda\envs\stan_env\lib\multiprocessing\context.py", line 322, in
_Popen
    return Popen(process_obj)
  File "D:\anaconda\envs\stan_env\lib\multiprocessing\popen_spawn_win32.py", lin
e 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda\envs\stan_env\lib\multiprocessing\reduction.py", line 60, in
 dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'BaseAsyncIOLoop.initialize.<locals>.a
ssign_thread_identity'
2020-05-25 09:01:51,790:INFO:configuration: Metric data rolling training window
size: 2 days, 23:59:59.934480
2020-05-25 09:01:51,791:INFO:configuration: Model retraining interval: 120 minut
es
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda\envs\stan_env\lib\multiprocessing\spawn.py", line 105, in sp
awn_main
    exitcode = _main(fd)
  File "D:\anaconda\envs\stan_env\lib\multiprocessing\spawn.py", line 115, in _m
ain
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

from the abover log ," Can't pickle local object 'BaseAsyncIOLoop.initialize.<locals>.a
ssign_thread_identity'"

maybe WINDOWS system ,lack of the "fork" process?

the demo just be runned in linux?

if there are only other solution methods will be very appreciated.Thanks a lot!

**Comment by 4n4nd** [comment]
Hey @frankcgq105 I am sorry I don't really have a windows system to test on :(

**Comment by 4n4nd** [comment]
@frankcgq105 Can you please try again with the latest commits?
If that doesn't work, I would recommend using the Dockerfile to build a container image and running it in a container.
