### ISSUE TITLE
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

### ISSUE THREAD

**Issue by tarakdatanow** [AICoE/prometheus-anomaly-detector#129]
Hi,

I'm facing this issue while using model_lstm. I've changed the "FLT_ROLLING_TRAINING_WINDOW_SIZE" to 10 days as per the script and metrics_list has two inputs. 

What changes am I missing to make, any suggestions are welcome.

config.py:

```
# How often should the anomaly detector retrain the model (in minutes)
    retraining_interval_minutes = int(
        os.getenv("FLT_RETRAINING_INTERVAL_MINUTES", "2")
    )
    metric_chunk_size = parse_timedelta("now", str(retraining_interval_minutes) + "m")

    _LOGGER.info(
        "Metric data rolling training window size: %s", rolling_training_window_size
    )
    _LOGGER.info("Model retraining interval: %s minutes", retraining_interval_minutes)
```

**Comment by 4n4nd** [comment]
thanks for letting us know, I will check it out :+1:

**Comment by 4n4nd** [comment]
@tarakdatanow I have updated some things in the tensorflow model (model_lstm), this should be fixed now. Could you please try again with the latest commits?

**Comment by tarakdatanow** [comment]
Same error @4n4nd 

`2020-10-12 11:56:10,435:INFO:configuration: Metric data rolling training window size: 9 days, 23:59:59.864357
2020-10-12 11:56:10,435:INFO:configuration: Model retraining interval: 10 minutes
2020-10-12 11:56:12.136092: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-12 11:56:12.136134: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-10-12 11:56:54.361686: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-10-12 11:56:54.361731: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-10-12 11:56:54.361764: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (tarak-Aspire): /proc/driver/nvidia/version does not exist
2020-10-12 11:56:54.400407: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2195200000 Hz
2020-10-12 11:56:54.400822: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x59e2a90 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-12 11:56:54.400859: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/home/tarak/Desktop/prometheus-anomaly-detector/app_lstm.py", line 160, in <module>
    train_model(initial_run=True, data_queue=predicted_model_queue)
  File "/home/tarak/Desktop/prometheus-anomaly-detector/app_lstm.py", line 142, in train_model
    predictor_model.train(
  File "/home/tarak/Desktop/prometheus-anomaly-detector/model_lstm.py", line 83, in train
    history = model.fit(x, y, epochs=50, batch_size=512, verbose=0,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 1049, in fit
    data_handler = data_adapter.DataHandler(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 1105, in __init__
    self._adapter = adapter_cls(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 265, in __init__
    x, y, sample_weights = _process_tensorlike((x, y, sample_weights))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 1021, in _process_tensorlike
    inputs = nest.map_structure(_convert_numpy_and_scipy, inputs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/nest.py", line 635, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/nest.py", line 635, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 1016, in _convert_numpy_and_scipy
    return ops.convert_to_tensor(x, dtype=dtype)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/tensor_conversion_registry.py", line 52, in _default_conversion_function
    return constant_op.constant(value, dtype, name=name)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py", line 263, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py", line 275, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py", line 300, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).`

**Comment by 4n4nd** [comment]
@tarakdatanow could you please make sure that all the dependencies were updated according to the latest pipfile?

**Comment by 4n4nd** [comment]
Could you run `pip freeze` in your environment and post the output here?
Thanks

**Comment by tarakdatanow** [comment]
Got it @4n4nd it was the Tensorflow version I was using. Now I'm able to train it.

**Comment by 4n4nd** [comment]
@tarakdatanow do you mind closing this issue then? thanks!
