### ISSUE TITLE
Getting AttributeError: Can't pickle local object 'BaseAsyncIOLoop.initialize.<locals>.assign_thread_identity' error

### ISSUE THREAD

**Issue by rakeshostwal** [AICoE/prometheus-anomaly-detector#92]
When I am trying to run this project by setting up given parameters in the configuration document, I am getting the following error:

`
2019-12-23 14:51:57,447:INFO:configuration: Metric data rolling training window size: 2 days, 23:59:59.937040
2019-12-23 14:51:57,448:INFO:configuration: Model retraining interval: 120 minutes
2019-12-23 14:51:58,738:ERROR:fbprophet: Importing plotly failed. Interactive plots will not work.
2019-12-23 14:51:59,656:INFO:__main__: Initializing Tornado Web App
Traceback (most recent call last):
  File "app.py", line 166, in <module>
    server_process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'BaseAsyncIOLoop.initialize.<locals>.assign_thread_identity'
`

I tried looking into the Process object but did not get any significant root cause. Can someone let me know if i am doing something wrong here? Thanks

**Comment by rakeshostwal** [comment]
This was coming due to the Conda configuration. Solved now.

**Comment by Carmezim** [comment]
I am getting the same error, not using conda though.

**Comment by latelan** [comment]
> This was coming due to the Conda configuration. Solved now.
@Carmezim I got the same error, how you resolve the problem

**Comment by ieasydevops** [comment]
![image](https://user-images.githubusercontent.com/4316534/160969813-729d176a-a5eb-4705-b200-017156ab3f7c.png)

I am getting the same error
